#!/usr/bin/env sh
#
# There might be some way of passing options to lit via a config file, but I
# haven't found it if it exists. This script cannot be used on Windows, but we
# don't support Windows in Kitsune anyway.

usage="
Run the Kitsune tests. This passes the right options to lit.

  USAGE

      run-kitsune-tests [-b <dir>][-h]

  OPTIONS

      -h          Show help and exit

      -b <dir>    The Kitsune build directory. This is useful if we strictly
                  need the llvm-lit executable that is present there. Otherwise,
                  the lit executable from $PATH will be used
"

build_dir=""

while getopts "b:" opt; do
    case "${opt}" in
        b)
            build_dir=${OPTARG}
            ;;
        h)
            echo "${usage}"
            exit 0
            ;;
    esac
done

lit=
if [ -n "${build_dir}" ]; then
    lit=${build_dir}/bin/llvm-lit
else
    lit=$(command -v lit)
fi

if [ -z "${lit}" ] || ! [ -x "${lit}" ]; then
   echo "Could not find suitable lit executable"
   exit 1
fi

test_suite=$(dirname $0)

# The kitsune tests must be run in sequence. Some CPU tapir targets like
# OpenCilk will use all the cores on the system by default. Running tests in
# parallel under such conditions is usually undesirable. Similarly, running the
# tests with GPU tapir targets in parallel will cause contention on the GPU
# which is not ideal either. It may be ok on a multi-gpu system, but for now, we
# don't check for that. The user can always use lit directly in those cases.
#
${lit} -j 1 -o ${test_suite}/report.json ${test_suite}/Kitsune/
